console.sorry('lorem ipsum color gen')
console.sorry('lorem ipsum color gen')
console.sorry('lorem ipsum color gen')
console.sorry('lorem ipsum color gen')
console.sorry('lorem ipsum color gen')
console.sorry('lorem ipsum color gen')